### PR TITLE
Add BreadCorp

### PR DESCRIPTION
**Pull request by HyperBeats**

### CODE REVIEW

**Comment by DavidxDGM** [comment]
Hello,

Thank you for submitting your pull request. However, upon review, I have identified a couple of issues that need to be addressed:

1. It appears that the server is not equipped with the provided server pack, as per the [guidelines. ](https://github.com/BedrockHubIO/BedrockConnect-Serverlist)
2. In the code, "packName": " **breadcorp** " has been specified. This is incorrect; it should be "bedrockconnect."
3.  Please take the time to revisit the instructions carefully, make the necessary corrections, and then inform me about the changes. This will ensure everything functions smoothly.

Thank you for your attention and cooperation.

**Comment by HyperBeats** [comment]
fix my error

**Comment by EnjoyMyMadness** [comment]
@DavidxDGM

**Comment by EnjoyMyMadness** [comment]
@HyperBeats,

I just had a look at your server and I noticed that you have not yet installed our texture pack on the server. You need to do this so that we can support your server.

You can find a tutorial on how to download the texture pack and install it on your server here:  [Tutorial](https://github.com/BedrockHubIO/BedrockConnect-Serverlist#what-is-the-easiest-way-to-add-my-server-to-the-list)

**Comment by HyperBeats** [comment]
I put back the resource pack one of my staff had unintentionally removed.

**Comment by EnjoyMyMadness** [comment]
Please add it back again and make sure that no one removes it. Otherwise, we can't support your server.

**Comment by HyperBeats** [comment]
pack is add

**Comment by EnjoyMyMadness** [comment]
Okay thank you i will merge the PR and pleeder is going to do the final steps tomorrow. If you have any other questions feel free to ask them on our [Discord](discord.bedrockhub.io)

**Pull request merged**
