### PR TITLE
add meowvanilla

### PR DESCRIPTION
**Pull request by RewardedIvan**

### CODE REVIEW

**Comment by DavidxDGM** [comment]
Hey, unfortunately the server cannot appear in the support list because the server pack described in the documentation is not currently installed on the Bedrock server (Geyser) or perhaps it has not been restarted?

**Comment by RewardedIvan** [comment]
I restarted the server, now it should be there

**Comment by DavidxDGM** [comment]
Nope, 
please follow these conditions:

That Pack: https://pack.bedrockhub.io/bedrockconnect

 [Geyser](https://discord.com/invite/geysermc):

- Move the file to geyser-spigot/packs/ and restart the server.

Do not unzip, but leave a .zip file!

**Comment by RewardedIvan** [comment]
oop i forgot that we are using velocity, now i added the pack to the proxy and restarted the proxy.

**Comment by DavidxDGM** [comment]
it works!

**Pull request merged**
